import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/presentation/components/toast/toaster";
import AuthProvider from "./app/layout";
import ReactQueryProvider from "./_providers/reactQueryProvider";
import { UserAccountStoreProvider } from "./_providers/userAccountStoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <UserAccountStoreProvider>
          <ReactQueryProvider>
            <body className={inter.className}>
              <main>
                {children}
              </main>

              <Toaster />
            </body>
          </ReactQueryProvider>
        </UserAccountStoreProvider>
      </AuthProvider>
    </html>
  );
}
