
// form options for the project form dialog
export const GOOGLE_SEARCH_CAMPAIGN_LANGUAGE_OPTIONS = [
  { value: "ar", label: "Arabic", criterionId: 1019 },
  { value: "bn", label: "Bengali", criterionId: 1056 },
  { value: "bg", label: "Bulgarian", criterionId: 1020 },
  { value: "ca", label: "Catalan", criterionId: 1038 },
  { value: "zh_CN", label: "Chinese (simplified)", criterionId: 1017 },
  { value: "zh_TW", label: "Chinese (traditional)", criterionId: 1018 },
  { value: "hr", label: "Croatian", criterionId: 1039 },
  { value: "cs", label: "Czech", criterionId: 1021 },
  { value: "da", label: "Danish", criterionId: 1009 },
  { value: "nl", label: "Dutch", criterionId: 1010 },
  { value: "en", label: "English", criterionId: 1000 },
  { value: "et", label: "Estonian", criterionId: 1043 },
  { value: "tl", label: "Filipino", criterionId: 1042 },
  { value: "fi", label: "Finnish", criterionId: 1011 },
  { value: "fr", label: "French", criterionId: 1002 },
  { value: "de", label: "German", criterionId: 1001 },
  { value: "el", label: "Greek", criterionId: 1022 },
  { value: "gu", label: "Gujarati", criterionId: 1072 },
  { value: "iw", label: "Hebrew", criterionId: 1027 },
  { value: "hi", label: "Hindi", criterionId: 1023 },
  { value: "hu", label: "Hungarian", criterionId: 1024 },
  { value: "is", label: "Icelandic", criterionId: 1026 },
  { value: "id", label: "Indonesian", criterionId: 1025 },
  { value: "it", label: "Italian", criterionId: 1004 },
  { value: "ja", label: "Japanese", criterionId: 1005 },
  { value: "kn", label: "Kannada", criterionId: 1086 },
  { value: "ko", label: "Korean", criterionId: 1012 },
  { value: "lv", label: "Latvian", criterionId: 1028 },
  { value: "lt", label: "Lithuanian", criterionId: 1029 },
  { value: "ms", label: "Malay", criterionId: 1102 },
  { value: "ml", label: "Malayalam", criterionId: 1098 },
  { value: "mr", label: "Marathi", criterionId: 1101 },
  { value: "no", label: "Norwegian", criterionId: 1013 },
  { value: "fa", label: "Persian", criterionId: 1064 },
  { value: "pl", label: "Polish", criterionId: 1030 },
  { value: "pt", label: "Portuguese", criterionId: 1014 },
  { value: "pa", label: "Punjabi", criterionId: 1110 },
  { value: "ro", label: "Romanian", criterionId: 1032 },
  { value: "ru", label: "Russian", criterionId: 1031 },
  { value: "sr", label: "Serbian", criterionId: 1035 },
  { value: "sk", label: "Slovak", criterionId: 1033 },
  { value: "sl", label: "Slovenian", criterionId: 1034 },
  { value: "es", label: "Spanish", criterionId: 1003 },
  { value: "sv", label: "Swedish", criterionId: 1015 },
  { value: "ta", label: "Tamil", criterionId: 1130 },
  { value: "te", label: "Telugu", criterionId: 1131 },
  { value: "th", label: "Thai", criterionId: 1044 },
  { value: "tr", label: "Turkish", criterionId: 1037 },
  { value: "uk", label: "Ukrainian", criterionId: 1036 },
  { value: "ur", label: "Urdu", criterionId: 1041 },
  { value: "vi", label: "Vietnamese", criterionId: 1040 }
];

export const GOOGLE_SEARCH_CAMPAIGN_CONTRIES_OPTIONS = [
  { value: "AF", label: "Afghanistan", criterionId: 2004},
  { value: "AL", label: "Albania", criterionId: 2008},
  { value: "AQ", label: "Antarctica", criterionId: 2010},
  { value: "DZ", label: "Algeria", criterionId: 2012},
  { value: "AS", label: "American Samoa", criterionId: 2016},
  { value: "AD", label: "Andorra", criterionId: 2020},
  { value: "AO", label: "Angola", criterionId: 2024},
  { value: "AG", label: "Antigua and Barbuda", criterionId: 2028},
  { value: "AZ", label: "Azerbaijan", criterionId: 2031},
  { value: "AR", label: "Argentina", criterionId: 2032},
  { value: "AU", label: "Australia", criterionId: 2036},
  { value: "AT", label: "Austria", criterionId: 2040},
  { value: "BS", label: "Bahamas", criterionId: 2044},
  { value: "BH", label: "Bahrain", criterionId: 2048},
  { value: "BD", label: "Bangladesh", criterionId: 2050},
  { value: "AM", label: "Armenia", criterionId: 2051},
  { value: "BB", label: "Barbados", criterionId: 2052},
  { value: "BE", label: "Belgium", criterionId: 2056},
  { value: "BT", label: "Bhutan", criterionId: 2064},
  { value: "BO", label: "Bolivia", criterionId: 2068},
  { value: "BA", label: "Bosnia and Herzegovina", criterionId: 2070},
  { value: "BW", label: "Botswana", criterionId: 2072},
  { value: "BR", label: "Brazil", criterionId: 2076},
  { value: "BZ", label: "Belize", criterionId: 2084},
  { value: "SB", label: "Solomon Islands", criterionId: 2090},
  { value: "BN", label: "Brunei", criterionId: 2096},
  { value: "BG", label: "Bulgaria", criterionId: 2100},
  { value: "MM", label: "Myanmar", criterionId: 2104},
  { value: "BI", label: "Burundi", criterionId: 2108},
  { value: "BY", label: "Belarus", criterionId: 2112},
  { value: "KH", label: "Cambodia", criterionId: 2116},
  { value: "CM", label: "Cameroon", criterionId: 2120},
  { value: "CA", label: "Canada", criterionId: 2124},
  { value: "CV", label: "Cape Verde", criterionId: 2132},
  { value: "CF", label: "Central African Republic", criterionId: 2140},
  { value: "LK", label: "Sri Lanka", criterionId: 2144},
  { value: "TD", label: "Chad", criterionId: 2148},
  { value: "CL", label: "Chile", criterionId: 2152},
  { value: "CN", label: "China", criterionId: 2156},
  { value: "CX", label: "Christmas Island", criterionId: 2162},
  { value: "CC", label: "Cocos (Keeling) Islands", criterionId: 2166},
  { value: "CO", label: "Colombia", criterionId: 2170},
  { value: "KM", label: "Comoros", criterionId: 2174},
  { value: "CG", label: "Congo", criterionId: 2178},
  { value: "CD", label: "Democratic Republic of the Congo", criterionId: 2180},
  { value: "CK", label: "Cook Islands", criterionId: 2184},
  { value: "CR", label: "Costa Rica", criterionId: 2188},
  { value: "HR", label: "Croatia", criterionId: 2191},
  { value: "CY", label: "Cyprus", criterionId: 2196},
  { value: "CZ", label: "Czech Republic", criterionId: 2203},
  { value: "BJ", label: "Benin", criterionId: 2204},
  { value: "DK", label: "Denmark", criterionId: 2208},
  { value: "DM", label: "Dominica", criterionId: 2212},
  { value: "DO", label: "Dominican Republic", criterionId: 2214},
  { value: "EC", label: "Ecuador", criterionId: 2218},
  { value: "SV", label: "El Salvador", criterionId: 2222},
  { value: "GQ", label: "Equatorial Guinea", criterionId: 2226},
  { value: "ET", label: "Ethiopia", criterionId: 2231},
  { value: "ER", label: "Eritrea", criterionId: 2232},
  { value: "EE", label: "Estonia", criterionId: 2233},
  { value: "GS", label: "South Georgia and the South Sandwich Islands", criterionId: 2239},
  { value: "FJ", label: "Fiji", criterionId: 2242},
  { value: "FI", label: "Finland", criterionId: 2246},
  { value: "FR", label: "France", criterionId: 2250},
  { value: "PF", label: "French Polynesia", criterionId: 2258},
  { value: "TF", label: "French Southern Territories", criterionId: 2260},
  { value: "DJ", label: "Djibouti", criterionId: 2262},
  { value: "GA", label: "Gabon", criterionId: 2266},
  { value: "GE", label: "Georgia", criterionId: 2268},
  { value: "GM", label: "Gambia", criterionId: 2270},
  { value: "DE", label: "Germany", criterionId: 2276},
  { value: "GH", label: "Ghana", criterionId: 2288},
  { value: "KI", label: "Kiribati", criterionId: 2296},
  { value: "GR", label: "Greece", criterionId: 2300},
  { value: "GD", label: "Grenada", criterionId: 2308},
  { value: "GU", label: "Guam", criterionId: 2316},
  { value: "GT", label: "Guatemala", criterionId: 2320},
  { value: "GN", label: "Guinea", criterionId: 2324},
  { value: "GY", label: "Guyana", criterionId: 2328},
  { value: "HT", label: "Haiti", criterionId: 2332},
  { value: "HM", label: "Heard Island and McDonald Islands", criterionId: 2334},
  { value: "VA", label: "Vatican", criterionId: 2336},
  { value: "HN", label: "Honduras", criterionId: 2340},
  { value: "HU", label: "Hungary", criterionId: 2348},
  { value: "IS", label: "Iceland", criterionId: 2352},
  { value: "IN", label: "India", criterionId: 2356},
  { value: "ID", label: "Indonesia", criterionId: 2360},
  { value: "IQ", label: "Iraq", criterionId: 2368},
  { value: "IE", label: "Ireland", criterionId: 2372},
  { value: "IL", label: "Israel", criterionId: 2376},
  { value: "IT", label: "Italy", criterionId: 2380},
  { value: "CI", label: "Ivory Coast", criterionId: 2384},
  { value: "JM", label: "Jamaica", criterionId: 2388},
  { value: "JP", label: "Japan", criterionId: 2392},
  { value: "KZ", label: "Kazakhstan", criterionId: 2398},
  { value: "JO", label: "Jordan", criterionId: 2400},
  { value: "KE", label: "Kenya", criterionId: 2404},
  { value: "KR", label: "South Korea", criterionId: 2410},
  { value: "KW", label: "Kuwait", criterionId: 2414},
  { value: "KG", label: "Kyrgyzstan", criterionId: 2417},
  { value: "LA", label: "Laos", criterionId: 2418},
  { value: "LB", label: "Lebanon", criterionId: 2422},
  { value: "LS", label: "Lesotho", criterionId: 2426},
  { value: "LV", label: "Latvia", criterionId: 2428},
  { value: "LR", label: "Liberia", criterionId: 2430},
  { value: "LY", label: "Libya", criterionId: 2434},
  { value: "LI", label: "Liechtenstein", criterionId: 2438},
  { value: "LT", label: "Lithuania", criterionId: 2440},
  { value: "LU", label: "Luxembourg", criterionId: 2442},
  { value: "MG", label: "Madagascar", criterionId: 2450},
  { value: "MW", label: "Malawi", criterionId: 2454},
  { value: "MY", label: "Malaysia", criterionId: 2458},
  { value: "MV", label: "Maldives", criterionId: 2462},
  { value: "ML", label: "Mali", criterionId: 2466},
  { value: "MT", label: "Malta", criterionId: 2470},
  { value: "MR", label: "Mauritania", criterionId: 2478},
  { value: "MU", label: "Mauritius", criterionId: 2480},
  { value: "MX", label: "Mexico", criterionId: 2484},
  { value: "MC", label: "Monaco", criterionId: 2492},
  { value: "MN", label: "Mongolia", criterionId: 2496},
  { value: "MD", label: "Moldova", criterionId: 2498},
  { value: "ME", label: "Montenegro", criterionId: 2499},
  { value: "MA", label: "Morocco", criterionId: 2504},
  { value: "MZ", label: "Mozambique", criterionId: 2508},
  { value: "OM", label: "Oman", criterionId: 2512},
  { value: "NA", label: "Namibia", criterionId: 2516},
  { value: "NR", label: "Nauru", criterionId: 2520},
  { value: "NP", label: "Nepal", criterionId: 2524},
  { value: "NL", label: "Netherlands", criterionId: 2528},
  { value: "BQ", label: "Bonaire", criterionId: 2535},
  { value: "CW", label: "Curaçao", criterionId: 2531},
  { value: "SX", label: "Sint Maarten", criterionId: 2534},
  { value: "NC", label: "New Caledonia", criterionId: 2540},
  { value: "VU", label: "Vanuatu", criterionId: 2548},
  { value: "NZ", label: "New Zealand", criterionId: 2554},
  { value: "NI", label: "Nicaragua", criterionId: 2558},
  { value: "NE", label: "Niger", criterionId: 2562},
  { value: "NG", label: "Nigeria", criterionId: 2566},
  { value: "NU", label: "Niue", criterionId: 2570},
  { value: "NF", label: "Norfolk Island", criterionId: 2574},
  { value: "NO", label: "Norway", criterionId: 2578},
  { value: "MP", label: "Northern Mariana Islands", criterionId: 2580},
  { value: "UM", label: "United States Minor Outlying Islands", criterionId: 2581},
  { value: "FM", label: "Micronesia", criterionId: 2583},
  { value: "MH", label: "Marshall Islands", criterionId: 2584},
  { value: "PW", label: "Palau", criterionId: 2585},
  { value: "PK", label: "Pakistan", criterionId: 2586},
  { value: "PA", label: "Panama", criterionId: 2591},
  { value: "PG", label: "Papua New Guinea", criterionId: 2598},
  { value: "PY", label: "Paraguay", criterionId: 2600},
  { value: "PE", label: "Peru", criterionId: 2604},
  { value: "PH", label: "Philippines", criterionId: 2608},
  { value: "PN", label: "Pitcairn Islands", criterionId: 2612},
  { value: "PL", label: "Poland", criterionId: 2616},
  { value: "PT", label: "Portugal", criterionId: 2620},
  { value: "GW", label: "Guinea-Bissau", criterionId: 2624},
  { value: "TL", label: "Timor-Leste", criterionId: 2626},
  { value: "QA", label: "Qatar", criterionId: 2634},
  { value: "RO", label: "Romania", criterionId: 2642},
  { value: "RU", label: "Russia", criterionId: 2643},
  { value: "RW", label: "Rwanda", criterionId: 2646},
  { value: "SH", label: "Saint Helena", criterionId: 2654},
  { value: "KN", label: "Saint Kitts and Nevis", criterionId: 2659},
  { value: "LC", label: "Saint Lucia", criterionId: 2662},
  { value: "PM", label: "Saint Pierre and Miquelon", criterionId: 2666},
  { value: "VC", label: "Saint Vincent and the Grenadines", criterionId: 2670},
  { value: "SM", label: "San Marino", criterionId: 2674},
  { value: "ST", label: "São Tomé and Príncipe", criterionId: 2678},
  { value: "SA", label: "Saudi Arabia", criterionId: 2682},
  { value: "SN", label: "Senegal", criterionId: 2686},
  { value: "RS", label: "Serbia", criterionId: 2688},
  { value: "SC", label: "Seychelles", criterionId: 2690},
  { value: "SL", label: "Sierra Leone", criterionId: 2694},
  { value: "SG", label: "Singapore", criterionId: 2702},
  { value: "SK", label: "Slovakia", criterionId: 2703},
  { value: "VN", label: "Vietnam", criterionId: 2704},
  { value: "SI", label: "Slovenia", criterionId: 2705},
  { value: "SO", label: "Somalia", criterionId: 2706},
  { value: "ZA", label: "South Africa", criterionId: 2710},
  { value: "ZW", label: "Zimbabwe", criterionId: 2716},
  { value: "ES", label: "Spain", criterionId: 2724},
  { value: "SR", label: "Suriname", criterionId: 2740},
  { value: "SZ", label: "Eswatini", criterionId: 2748},
  { value: "SE", label: "Sweden", criterionId: 2752},
  { value: "CH", label: "Switzerland", criterionId: 2756},
  { value: "TJ", label: "Tajikistan", criterionId: 2762},
  { value: "TH", label: "Thailand", criterionId: 2764},
  { value: "TG", label: "Togo", criterionId: 2768},
  { value: "TK", label: "Tokelau", criterionId: 2772},
  { value: "TO", label: "Tonga", criterionId: 2776},
  { value: "TT", label: "Trinidad and Tobago", criterionId: 2780},
  { value: "AE", label: "United Arab Emirates", criterionId: 2784},
  { value: "TN", label: "Tunisia", criterionId: 2788},
  { value: "TR", label: "Turkey", criterionId: 2792},
  { value: "TM", label: "Turkmenistan", criterionId: 2795},
  { value: "TV", label: "Tuvalu", criterionId: 2798},
  { value: "UG", label: "Uganda", criterionId: 2800},
  { value: "UA", label: "Ukraine", criterionId: 2804},
  { value: "MK", label: "North Macedonia", criterionId: 2807},
  { value: "EG", label: "Egypt", criterionId: 2818},
  { value: "GB", label: "United Kingdom", criterionId: 2826},
  { value: "GG", label: "Guernsey", criterionId: 2831},
  { value: "JE", label: "Jersey", criterionId: 2832},
  { value: "TZ", label: "Tanzania", criterionId: 2834},
  { value: "US", label: "United States", criterionId: 2840},
  { value: "BF", label: "Burkina Faso", criterionId: 2854},
  { value: "UY", label: "Uruguay", criterionId: 2858},
  { value: "UZ", label: "Uzbekistan", criterionId: 2860},
  { value: "VE", label: "Venezuela", criterionId: 2862},
  { value: "WF", label: "Wallis and Futuna", criterionId: 2876},
  { value: "WS", label: "Samoa", criterionId: 2882},
  { value: "YE", label: "Yemen", criterionId: 2887},
  { value: "ZM", label: "Zambia", criterionId: 2894}
];

export type DayOfWeek = "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
export const DAYS_OF_WEEK: {value: DayOfWeek; label: string}[] = [
  { value: "MONDAY", label: "Monday" },
  { value: "TUESDAY", label: "Tuesday" },
  { value: "WEDNESDAY", label: "Wednesday" },
  { value: "THURSDAY", label: "Thursday" },
  { value: "FRIDAY", label: "Friday" },
  { value: "SATURDAY", label: "Saturday" },
  { value: "SUNDAY", label: "Sunday" },
];