
// form options for the project form dialog
export type GoogleSearchLanguage = { 
  countryCode: string; 
  name: string; 
  googleId: number;
};

export const GOOGLE_SEARCH_CAMPAIGN_LANGUAGE_OPTIONS = [
  { countryCode: "ar", name: "Arabic", googleId: 1019 },
  { countryCode: "bn", name: "Bengali", googleId: 1056 },
  { countryCode: "bg", name: "Bulgarian", googleId: 1020 },
  { countryCode: "ca", name: "Catalan", googleId: 1038 },
  { countryCode: "zh_CN", name: "Chinese (simplified)", googleId: 1017 },
  { countryCode: "zh_TW", name: "Chinese (traditional)", googleId: 1018 },
  { countryCode: "hr", name: "Croatian", googleId: 1039 },
  { countryCode: "cs", name: "Czech", googleId: 1021 },
  { countryCode: "da", name: "Danish", googleId: 1009 },
  { countryCode: "nl", name: "Dutch", googleId: 1010 },
  { countryCode: "en", name: "English", googleId: 1000 },
  { countryCode: "et", name: "Estonian", googleId: 1043 },
  { countryCode: "tl", name: "Filipino", googleId: 1042 },
  { countryCode: "fi", name: "Finnish", googleId: 1011 },
  { countryCode: "fr", name: "French", googleId: 1002 },
  { countryCode: "de", name: "German", googleId: 1001 },
  { countryCode: "el", name: "Greek", googleId: 1022 },
  { countryCode: "gu", name: "Gujarati", googleId: 1072 },
  { countryCode: "iw", name: "Hebrew", googleId: 1027 },
  { countryCode: "hi", name: "Hindi", googleId: 1023 },
  { countryCode: "hu", name: "Hungarian", googleId: 1024 },
  { countryCode: "is", name: "Icelandic", googleId: 1026 },
  { countryCode: "id", name: "Indonesian", googleId: 1025 },
  { countryCode: "it", name: "Italian", googleId: 1004 },
  { countryCode: "ja", name: "Japanese", googleId: 1005 },
  { countryCode: "kn", name: "Kannada", googleId: 1086 },
  { countryCode: "ko", name: "Korean", googleId: 1012 },
  { countryCode: "lv", name: "Latvian", googleId: 1028 },
  { countryCode: "lt", name: "Lithuanian", googleId: 1029 },
  { countryCode: "ms", name: "Malay", googleId: 1102 },
  { countryCode: "ml", name: "Malayalam", googleId: 1098 },
  { countryCode: "mr", name: "Marathi", googleId: 1101 },
  { countryCode: "no", name: "Norwegian", googleId: 1013 },
  { countryCode: "fa", name: "Persian", googleId: 1064 },
  { countryCode: "pl", name: "Polish", googleId: 1030 },
  { countryCode: "pt", name: "Portuguese", googleId: 1014 },
  { countryCode: "pa", name: "Punjabi", googleId: 1110 },
  { countryCode: "ro", name: "Romanian", googleId: 1032 },
  { countryCode: "ru", name: "Russian", googleId: 1031 },
  { countryCode: "sr", name: "Serbian", googleId: 1035 },
  { countryCode: "sk", name: "Slovak", googleId: 1033 },
  { countryCode: "sl", name: "Slovenian", googleId: 1034 },
  { countryCode: "es", name: "Spanish", googleId: 1003 },
  { countryCode: "sv", name: "Swedish", googleId: 1015 },
  { countryCode: "ta", name: "Tamil", googleId: 1130 },
  { countryCode: "te", name: "Telugu", googleId: 1131 },
  { countryCode: "th", name: "Thai", googleId: 1044 },
  { countryCode: "tr", name: "Turkish", googleId: 1037 },
  { countryCode: "uk", name: "Ukrainian", googleId: 1036 },
  { countryCode: "ur", name: "Urdu", googleId: 1041 },
  { countryCode: "vi", name: "Vietnamese", googleId: 1040 }
];

export type GoogleSearchCountry = {
  countryCode: string;
  name: string;
  googleId: number;
};
export const GOOGLE_SEARCH_CAMPAIGN_CONTRIES_OPTIONS = [
  { countryCode: "AF", name: "Afghanistan", googleId: 2004},
  { countryCode: "AL", name: "Albania", googleId: 2008},
  { countryCode: "AQ", name: "Antarctica", googleId: 2010},
  { countryCode: "DZ", name: "Algeria", googleId: 2012},
  { countryCode: "AS", name: "American Samoa", googleId: 2016},
  { countryCode: "AD", name: "Andorra", googleId: 2020},
  { countryCode: "AO", name: "Angola", googleId: 2024},
  { countryCode: "AG", name: "Antigua and Barbuda", googleId: 2028},
  { countryCode: "AZ", name: "Azerbaijan", googleId: 2031},
  { countryCode: "AR", name: "Argentina", googleId: 2032},
  { countryCode: "AU", name: "Australia", googleId: 2036},
  { countryCode: "AT", name: "Austria", googleId: 2040},
  { countryCode: "BS", name: "Bahamas", googleId: 2044},
  { countryCode: "BH", name: "Bahrain", googleId: 2048},
  { countryCode: "BD", name: "Bangladesh", googleId: 2050},
  { countryCode: "AM", name: "Armenia", googleId: 2051},
  { countryCode: "BB", name: "Barbados", googleId: 2052},
  { countryCode: "BE", name: "Belgium", googleId: 2056},
  { countryCode: "BT", name: "Bhutan", googleId: 2064},
  { countryCode: "BO", name: "Bolivia", googleId: 2068},
  { countryCode: "BA", name: "Bosnia and Herzegovina", googleId: 2070},
  { countryCode: "BW", name: "Botswana", googleId: 2072},
  { countryCode: "BR", name: "Brazil", googleId: 2076},
  { countryCode: "BZ", name: "Belize", googleId: 2084},
  { countryCode: "SB", name: "Solomon Islands", googleId: 2090},
  { countryCode: "BN", name: "Brunei", googleId: 2096},
  { countryCode: "BG", name: "Bulgaria", googleId: 2100},
  { countryCode: "MM", name: "Myanmar", googleId: 2104},
  { countryCode: "BI", name: "Burundi", googleId: 2108},
  { countryCode: "BY", name: "Belarus", googleId: 2112},
  { countryCode: "KH", name: "Cambodia", googleId: 2116},
  { countryCode: "CM", name: "Cameroon", googleId: 2120},
  { countryCode: "CA", name: "Canada", googleId: 2124},
  { countryCode: "CV", name: "Cape Verde", googleId: 2132},
  { countryCode: "CF", name: "Central African Republic", googleId: 2140},
  { countryCode: "LK", name: "Sri Lanka", googleId: 2144},
  { countryCode: "TD", name: "Chad", googleId: 2148},
  { countryCode: "CL", name: "Chile", googleId: 2152},
  { countryCode: "CN", name: "China", googleId: 2156},
  { countryCode: "CX", name: "Christmas Island", googleId: 2162},
  { countryCode: "CC", name: "Cocos (Keeling) Islands", googleId: 2166},
  { countryCode: "CO", name: "Colombia", googleId: 2170},
  { countryCode: "KM", name: "Comoros", googleId: 2174},
  { countryCode: "CG", name: "Congo", googleId: 2178},
  { countryCode: "CD", name: "Democratic Republic of the Congo", googleId: 2180},
  { countryCode: "CK", name: "Cook Islands", googleId: 2184},
  { countryCode: "CR", name: "Costa Rica", googleId: 2188},
  { countryCode: "HR", name: "Croatia", googleId: 2191},
  { countryCode: "CY", name: "Cyprus", googleId: 2196},
  { countryCode: "CZ", name: "Czech Republic", googleId: 2203},
  { countryCode: "BJ", name: "Benin", googleId: 2204},
  { countryCode: "DK", name: "Denmark", googleId: 2208},
  { countryCode: "DM", name: "Dominica", googleId: 2212},
  { countryCode: "DO", name: "Dominican Republic", googleId: 2214},
  { countryCode: "EC", name: "Ecuador", googleId: 2218},
  { countryCode: "SV", name: "El Salvador", googleId: 2222},
  { countryCode: "GQ", name: "Equatorial Guinea", googleId: 2226},
  { countryCode: "ET", name: "Ethiopia", googleId: 2231},
  { countryCode: "ER", name: "Eritrea", googleId: 2232},
  { countryCode: "EE", name: "Estonia", googleId: 2233},
  { countryCode: "GS", name: "South Georgia and the South Sandwich Islands", googleId: 2239},
  { countryCode: "FJ", name: "Fiji", googleId: 2242},
  { countryCode: "FI", name: "Finland", googleId: 2246},
  { countryCode: "FR", name: "France", googleId: 2250},
  { countryCode: "PF", name: "French Polynesia", googleId: 2258},
  { countryCode: "TF", name: "French Southern Territories", googleId: 2260},
  { countryCode: "DJ", name: "Djibouti", googleId: 2262},
  { countryCode: "GA", name: "Gabon", googleId: 2266},
  { countryCode: "GE", name: "Georgia", googleId: 2268},
  { countryCode: "GM", name: "Gambia", googleId: 2270},
  { countryCode: "DE", name: "Germany", googleId: 2276},
  { countryCode: "GH", name: "Ghana", googleId: 2288},
  { countryCode: "KI", name: "Kiribati", googleId: 2296},
  { countryCode: "GR", name: "Greece", googleId: 2300},
  { countryCode: "GD", name: "Grenada", googleId: 2308},
  { countryCode: "GU", name: "Guam", googleId: 2316},
  { countryCode: "GT", name: "Guatemala", googleId: 2320},
  { countryCode: "GN", name: "Guinea", googleId: 2324},
  { countryCode: "GY", name: "Guyana", googleId: 2328},
  { countryCode: "HT", name: "Haiti", googleId: 2332},
  { countryCode: "HM", name: "Heard Island and McDonald Islands", googleId: 2334},
  { countryCode: "VA", name: "Vatican", googleId: 2336},
  { countryCode: "HN", name: "Honduras", googleId: 2340},
  { countryCode: "HU", name: "Hungary", googleId: 2348},
  { countryCode: "IS", name: "Iceland", googleId: 2352},
  { countryCode: "IN", name: "India", googleId: 2356},
  { countryCode: "ID", name: "Indonesia", googleId: 2360},
  { countryCode: "IQ", name: "Iraq", googleId: 2368},
  { countryCode: "IE", name: "Ireland", googleId: 2372},
  { countryCode: "IL", name: "Israel", googleId: 2376},
  { countryCode: "IT", name: "Italy", googleId: 2380},
  { countryCode: "CI", name: "Ivory Coast", googleId: 2384},
  { countryCode: "JM", name: "Jamaica", googleId: 2388},
  { countryCode: "JP", name: "Japan", googleId: 2392},
  { countryCode: "KZ", name: "Kazakhstan", googleId: 2398},
  { countryCode: "JO", name: "Jordan", googleId: 2400},
  { countryCode: "KE", name: "Kenya", googleId: 2404},
  { countryCode: "KR", name: "South Korea", googleId: 2410},
  { countryCode: "KW", name: "Kuwait", googleId: 2414},
  { countryCode: "KG", name: "Kyrgyzstan", googleId: 2417},
  { countryCode: "LA", name: "Laos", googleId: 2418},
  { countryCode: "LB", name: "Lebanon", googleId: 2422},
  { countryCode: "LS", name: "Lesotho", googleId: 2426},
  { countryCode: "LV", name: "Latvia", googleId: 2428},
  { countryCode: "LR", name: "Liberia", googleId: 2430},
  { countryCode: "LY", name: "Libya", googleId: 2434},
  { countryCode: "LI", name: "Liechtenstein", googleId: 2438},
  { countryCode: "LT", name: "Lithuania", googleId: 2440},
  { countryCode: "LU", name: "Luxembourg", googleId: 2442},
  { countryCode: "MG", name: "Madagascar", googleId: 2450},
  { countryCode: "MW", name: "Malawi", googleId: 2454},
  { countryCode: "MY", name: "Malaysia", googleId: 2458},
  { countryCode: "MV", name: "Maldives", googleId: 2462},
  { countryCode: "ML", name: "Mali", googleId: 2466},
  { countryCode: "MT", name: "Malta", googleId: 2470},
  { countryCode: "MR", name: "Mauritania", googleId: 2478},
  { countryCode: "MU", name: "Mauritius", googleId: 2480},
  { countryCode: "MX", name: "Mexico", googleId: 2484},
  { countryCode: "MC", name: "Monaco", googleId: 2492},
  { countryCode: "MN", name: "Mongolia", googleId: 2496},
  { countryCode: "MD", name: "Moldova", googleId: 2498},
  { countryCode: "ME", name: "Montenegro", googleId: 2499},
  { countryCode: "MA", name: "Morocco", googleId: 2504},
  { countryCode: "MZ", name: "Mozambique", googleId: 2508},
  { countryCode: "OM", name: "Oman", googleId: 2512},
  { countryCode: "NA", name: "Namibia", googleId: 2516},
  { countryCode: "NR", name: "Nauru", googleId: 2520},
  { countryCode: "NP", name: "Nepal", googleId: 2524},
  { countryCode: "NL", name: "Netherlands", googleId: 2528},
  { countryCode: "BQ", name: "Bonaire", googleId: 2535},
  { countryCode: "CW", name: "Curaçao", googleId: 2531},
  { countryCode: "SX", name: "Sint Maarten", googleId: 2534},
  { countryCode: "NC", name: "New Caledonia", googleId: 2540},
  { countryCode: "VU", name: "Vanuatu", googleId: 2548},
  { countryCode: "NZ", name: "New Zealand", googleId: 2554},
  { countryCode: "NI", name: "Nicaragua", googleId: 2558},
  { countryCode: "NE", name: "Niger", googleId: 2562},
  { countryCode: "NG", name: "Nigeria", googleId: 2566},
  { countryCode: "NU", name: "Niue", googleId: 2570},
  { countryCode: "NF", name: "Norfolk Island", googleId: 2574},
  { countryCode: "NO", name: "Norway", googleId: 2578},
  { countryCode: "MP", name: "Northern Mariana Islands", googleId: 2580},
  { countryCode: "UM", name: "United States Minor Outlying Islands", googleId: 2581},
  { countryCode: "FM", name: "Micronesia", googleId: 2583},
  { countryCode: "MH", name: "Marshall Islands", googleId: 2584},
  { countryCode: "PW", name: "Palau", googleId: 2585},
  { countryCode: "PK", name: "Pakistan", googleId: 2586},
  { countryCode: "PA", name: "Panama", googleId: 2591},
  { countryCode: "PG", name: "Papua New Guinea", googleId: 2598},
  { countryCode: "PY", name: "Paraguay", googleId: 2600},
  { countryCode: "PE", name: "Peru", googleId: 2604},
  { countryCode: "PH", name: "Philippines", googleId: 2608},
  { countryCode: "PN", name: "Pitcairn Islands", googleId: 2612},
  { countryCode: "PL", name: "Poland", googleId: 2616},
  { countryCode: "PT", name: "Portugal", googleId: 2620},
  { countryCode: "GW", name: "Guinea-Bissau", googleId: 2624},
  { countryCode: "TL", name: "Timor-Leste", googleId: 2626},
  { countryCode: "QA", name: "Qatar", googleId: 2634},
  { countryCode: "RO", name: "Romania", googleId: 2642},
  { countryCode: "RU", name: "Russia", googleId: 2643},
  { countryCode: "RW", name: "Rwanda", googleId: 2646},
  { countryCode: "SH", name: "Saint Helena", googleId: 2654},
  { countryCode: "KN", name: "Saint Kitts and Nevis", googleId: 2659},
  { countryCode: "LC", name: "Saint Lucia", googleId: 2662},
  { countryCode: "PM", name: "Saint Pierre and Miquelon", googleId: 2666},
  { countryCode: "VC", name: "Saint Vincent and the Grenadines", googleId: 2670},
  { countryCode: "SM", name: "San Marino", googleId: 2674},
  { countryCode: "ST", name: "São Tomé and Príncipe", googleId: 2678},
  { countryCode: "SA", name: "Saudi Arabia", googleId: 2682},
  { countryCode: "SN", name: "Senegal", googleId: 2686},
  { countryCode: "RS", name: "Serbia", googleId: 2688},
  { countryCode: "SC", name: "Seychelles", googleId: 2690},
  { countryCode: "SL", name: "Sierra Leone", googleId: 2694},
  { countryCode: "SG", name: "Singapore", googleId: 2702},
  { countryCode: "SK", name: "Slovakia", googleId: 2703},
  { countryCode: "VN", name: "Vietnam", googleId: 2704},
  { countryCode: "SI", name: "Slovenia", googleId: 2705},
  { countryCode: "SO", name: "Somalia", googleId: 2706},
  { countryCode: "ZA", name: "South Africa", googleId: 2710},
  { countryCode: "ZW", name: "Zimbabwe", googleId: 2716},
  { countryCode: "ES", name: "Spain", googleId: 2724},
  { countryCode: "SR", name: "Suriname", googleId: 2740},
  { countryCode: "SZ", name: "Eswatini", googleId: 2748},
  { countryCode: "SE", name: "Sweden", googleId: 2752},
  { countryCode: "CH", name: "Switzerland", googleId: 2756},
  { countryCode: "TJ", name: "Tajikistan", googleId: 2762},
  { countryCode: "TH", name: "Thailand", googleId: 2764},
  { countryCode: "TG", name: "Togo", googleId: 2768},
  { countryCode: "TK", name: "Tokelau", googleId: 2772},
  { countryCode: "TO", name: "Tonga", googleId: 2776},
  { countryCode: "TT", name: "Trinidad and Tobago", googleId: 2780},
  { countryCode: "AE", name: "United Arab Emirates", googleId: 2784},
  { countryCode: "TN", name: "Tunisia", googleId: 2788},
  { countryCode: "TR", name: "Turkey", googleId: 2792},
  { countryCode: "TM", name: "Turkmenistan", googleId: 2795},
  { countryCode: "TV", name: "Tuvalu", googleId: 2798},
  { countryCode: "UG", name: "Uganda", googleId: 2800},
  { countryCode: "UA", name: "Ukraine", googleId: 2804},
  { countryCode: "MK", name: "North Macedonia", googleId: 2807},
  { countryCode: "EG", name: "Egypt", googleId: 2818},
  { countryCode: "GB", name: "United Kingdom", googleId: 2826},
  { countryCode: "GG", name: "Guernsey", googleId: 2831},
  { countryCode: "JE", name: "Jersey", googleId: 2832},
  { countryCode: "TZ", name: "Tanzania", googleId: 2834},
  { countryCode: "US", name: "United States", googleId: 2840},
  { countryCode: "BF", name: "Burkina Faso", googleId: 2854},
  { countryCode: "UY", name: "Uruguay", googleId: 2858},
  { countryCode: "UZ", name: "Uzbekistan", googleId: 2860},
  { countryCode: "VE", name: "Venezuela", googleId: 2862},
  { countryCode: "WF", name: "Wallis and Futuna", googleId: 2876},
  { countryCode: "WS", name: "Samoa", googleId: 2882},
  { countryCode: "YE", name: "Yemen", googleId: 2887},
  { countryCode: "ZM", name: "Zambia", googleId: 2894}
];

export type DayOfWeek = "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
export const DAYS_OF_WEEK: {value: DayOfWeek; label: string}[] = [
  { value: "MONDAY", label: "Monday" },
  { value: "TUESDAY", label: "Tuesday" },
  { value: "WEDNESDAY", label: "Wednesday" },
  { value: "THURSDAY", label: "Thursday" },
  { value: "FRIDAY", label: "Friday" },
  { value: "SATURDAY", label: "Saturday" },
  { value: "SUNDAY", label: "Sunday" },
];